title: Okonma's Website
description: My little corner on the internet
baseurl: /hacked-jekyll
url: https://piazzai.github.io

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
newtab: true
quotes: values
lowercase: keys